---
# tasks file for up-to-date

- name: Update apt cache
  become: true
  apt:
    update_cache: yes

- name: Dist-Upgrade apt packages
  become: true
  apt:
    upgrade: dist

- name: Remove apt unneeded packages
  become: true
  apt:
    autoremove: yes
    purge: yes

- name: Clean apt cache
  become: true
  apt:
    autoclean: yes

